### ISSUE TITLE
How to retrieve a post name associated with custom field?

### ISSUE THREAD

**Issue by ericleonardo** [athlan/wordpress-custom-fields-permalink-plugin#11]
I want to use store name in offer permalink.
But using /%field_offer_store%/ returns its store ID number, not its store post name.

Data on wp_posts:
- ID: 895
- post_title: Calvin Klein
- post_name: calvin-klein
- post_type: store

Data on wp_postmeta (the offer details):
- meta_key: offer_store
- meta_value: 895

Please, is there any way to custom field "offer_store" return its name from "wp_posts" instead of returning its ID number from "wp_postmeta"?

Best regards!
Eric

**Comment by athlan** [comment]
Hello Eric,

Thank you for contacting. Currently plugin uses [`get_post_meta`](https://developer.wordpress.org/reference/functions/get_post_meta/($post->ID)) to extract custom meta fields to generate the link. In the case you mentioned you need to provide somehow non-existing value in metadata database table.

You can achieve that on two ways:
1. More performant for reads - generate those values. It requires some data migration to fill data to existing content and bind to hooks when updating this metadata [`update_(meta_type)_metadata()`](https://codex.wordpress.org/Plugin_API/Filter_Reference/update_(meta_type)_metadata) and updating the store pagetype also.
2. Generate this value on-the-fly. This could impact performance because of additional query. Or you can hardcode values to increase performance. Use the hook [`get_(meta_type)_metadata`](https://codex.wordpress.org/Plugin_API/Filter_Reference/get_(meta_type)_metadata) and generate meta key you need and reuse in permalink generation.

We mentioned all about link generation. But plugin queries Wordpress also about meta keys used in links. It need at least exists and it could cause a problem while using dynamically generated meta keys to generate permalink.

They could be ignored (by introducing some feature in plugin), but there is a need to somehow identify the post by another process (like post id, the permalink).

What you think about:
* Use in permalink somethink that can distingush post (e.g. permalink)
* and generate meta values dynamically
* and make some plugin settings to ignore some meta fields to not use them in wp-query.

**Comment by athlan** [comment]
This issue will be addressed in https://github.com/athlan/wordpress-custom-fields-permalink-plugin/issues/13 and planned to 1.2.0 release.

**Comment by ericleonardo** [comment]
Very good! Currently, I'm using a trick. Added a custom field (ACF plugin) "store-name" and put store slug manually to eache post (my posts are updated by WP All Import + ACF add-on). Then, used your plugin to retrieve that custom field. I'll wait and try release 1.2 to avoid depending on manually input store slug. But for now, my trick is working...

Thanks!

**Comment by athlan** [comment]
Please be informed, that [1.2.0](https://github.com/athlan/wordpress-custom-fields-permalink-plugin/releases/tag/1.2.0) has been released.
